config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'entries/index'
  root to: 'events#index'
  resources :events do
    collection do
      get 'search'
    end
    resources :entries, only:[:index, :create]
    resource :likes, only:[:create, :destroy]
  end
  resources :users, only: [:show, :new] do
    member do
      get 'mypage'
    end
  end
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  with_options presence: true do
    validates :nickname
    validates :phone_number, format: { with: /\A\d{10,11}\z/, message: "は半角数字を入力してください" }
    validates :birth_day
    validates :area_id, numericality: { other_than: 1, message: "を選択してください" }
  end
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX, message: 'は英数字混合にしてください' }
  VALID_NAME_REGEX = /\A[ぁ-んァ-ヶ一-龥々]+\z/
  with_options presence: true, format: { with: VALID_NAME_REGEX, message: 'は全角文字で入力してください' } do
    validates :family_name
    validates :first_name
  end
  VALID_KANA_NAME_REGEX = /\A[ァ-ヶー－]+\z/
  with_options presence: true, format: { with: VALID_KANA_NAME_REGEX, message: "は全角カナ文字で入力してください" } do
    validates :kana_family_name
    validates :kana_first_name
  end

  has_many :events
  has_many :entries
  has_many :users
  has_many :sns_credentials
  has_many :likes, dependent: :destroy
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :area

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def entried_by?(event_id)
    entries.where(event_id: event_id).exists?
  end

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    user = User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    if user.persisted?
      sns.user = user
      sns.save
    end
    { user: user, sns: sns }
  end

  def already_liked?(event)
    self.likes.exists?(event_id: event.id)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
   authorization
  end
 
  def google_oauth2
   authorization
  end
 
  private
 
  def authorization
    sns_info = User.from_omniauth(request.env["omniauth.auth"])
    @user = sns_info[:user]

    if @user.persisted? 
      sign_in_and_redirect @user, event: :authentication
    else 
      @sns_id = sns_info[:sns].id
      render template: 'devise/registrations/new'
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_account_update_params, only: [:update]
  before_action :check_captcha, only: [:create]

  def create
    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def check_captcha
    self.resource = resource_class.new sign_up_params
    resource.validate
    unless verify_recaptcha(model: resource)
      respond_with_navigational(resource) { render :new }
    end
  end

  
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:family_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:kana_family_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:kana_first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:birth_day])
    devise_parameter_sanitizer.permit(:account_update, keys: [:area_id])
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:introduction])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:mypage]
  before_action :set_user, only:[:show, :mypage]
  before_action :move_to_index_edit, only:[:mypage]

  def show
    @events = @user.events.order("created_at DESC").page(params[:page]).per(6)
  end

  def mypage
  end

  def new
  end

  

  private

  def set_user
    @user = User.find(params[:id])
  end

  def move_to_index_edit
    if current_user.id != @user.id 
      redirect_to root_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/mypage.html.erb
<%= render "events/header-second" %>
<div class="events-main-contents">
  <div class="event-create-main">
    <h1 class="events-create-title"><%= @user.nickname %>さんのご登録内容</h1>
  </div> 
  <table class="events-table">
    <tbody>
      <tr>
        <th>
          ニックネーム
        </th>
        <td>
          <%= @user.nickname %>
        </td>
      </tr>
      <tr>
        <th>
          Eメール
        </th>
        <td>
          <%= @user.email %>
        </td>
      </tr>
      <tr>
        <th>
          パスワード
        </th>
        <td>
          *********(セキュリティー上表示しておりません)
        </td>
      </tr>
      <tr>
        <th>
          お名前
        </th>
        <td>
          <%= @user.family_name %> <%= @user.first_name %>
        </td>
      </tr>
      <tr>
        <th>
          お誕生日
        </th>
        <td>
          <%= @user.birth_day.year %>年<%= @user.birth_day.month %>月<%= @user.birth_day.day %>日
        </td>
      </tr>
      <tr>
        <th>
          お電話番号
        </th>
        <td>
          <%= @user.phone_number %>人
        </td>
      </tr>
      <tr>
        <th>
          自己紹介
        </th>
        <td>
          <%= @user.introduction %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="event-edit-btn">
    <%= link_to "登録内容の編集", edit_user_registration_path(@user.id), class: "user-edit-path-btn" %>
  </div>
</div>
<%= render "events/footer" %>

app/views/users/new.html.erb
<%= render "events/header-second" %>
<div class="events-main-contents">
  <div class="event-create-main">
    <h1 class="events-create-title">新規会員登録</h1>
    <div class="login-box-logo">
      <%= link_to new_user_registration_path, class:"email-box" do %>
        <i class="far fa-envelope"></i><p class="logo-font">メールアドレスで登録</p>
      <% end %>
      <%= link_to user_facebook_omniauth_authorize_path, method: :post, class:"facebook-logo" do %>
        <i class="fab fa-facebook"></i><p class="logo-font">Facebookで登録</p>
      <% end %>
      <%= link_to user_google_oauth2_omniauth_authorize_path, method: :post, class:"google-logo" do %>
        <i class="fab fa-google"></i><p class="logo-font">Googleで登録</p>
      <% end %>
    </div>
  </div>
</div>
<%= render "events/footer" %>

app/views/users/show.html.erb
<%= render "events/header-second" %>
<div class="events-main-contents">
  <div class="event-create-main">
    <h1 class="events-create-title"><%= @user.nickname %>さんの投稿一覧</h1>
  </div>
  <% if user_signed_in? %>
    <% if current_user.id == @user.id  %> 
      <%= link_to "ユーザー登録情報の確認",  mypage_user_path(@user.id), class: "user-edit-btn" %>
    <% end %>
  <% end %>
  <%if @events.present? %>
    <ul class="main-list">
        <% @events.each do |event|%>
          <li class="event-info">
            <div class="sports-genre">      
              <%= event.genre.name %>
            </div>
            <div class="sports-area">
              <%= event.area.name %>
            </div>
            <%= link_to event_path(event.id), class:"img-link" do %>
              <%= image_tag event.image.variant(resize: '500x400') %>
            <% end %>
            <h2 class="event-name"><%= link_to event.name, event_path(event.id), class:"event-name-font" %></h2>
            <dl class="event-exp">
              <dt>
                <img src="https://images.e-venz.com/frontend/image/location.svg" class="Location lazy" alt="Location">
              </dt>
              <dd><%= event.address %></dd>
              <dt>
                <img src="https://images.e-venz.com/frontend/image/women.svg" alt="Women" class="lazy">
              </dt>
              <dd><%= event.capacity %>人</dd>
              <dt>
                <img src="https://images.e-venz.com/frontend/image/calendar.svg" alt="Calendar" class="lazy">
              </dt>
              <dd><%= event.day.month %>月<%= event.day.day %>日 <%= event.start_time.name %> ~ <%= event.end_time.name %></dd>
              <%= render partial: "events/like", locals: { event: event } %>
            </dl>
            
          </li>
        <% end %>
        <%= paginate @events %>
    <ul>
  <% else %>
    <h2>まだ投稿がございません</h2>
  <% end %>
</div>
<%= render "events/footer" %>