config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  get 'entries/index'
  root to: 'events#index'
  resources :events do
    collection do
      get 'search'
    end
    resources :entries, only:[:index, :create]
    resource :likes, only:[:create, :destroy]
  end
  resources :users, only: [:show, :new] do
    member do
      get 'mypage'
    end
  end
  
  
end

app/models/event.rb
class Event < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  has_one_attached :image
  has_many :entries, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  belongs_to :area
  belongs_to :start_time
  belongs_to :end_time
  with_options presence: true do
    validates :name
    validates :image
    validates :explanation
    validates :day    
    validates :capacity
    validates :address
  end
  with_options numericality: { other_than: 1, message: "を選択してください" }, presence: true do
    validates :genre_id
    validates :area_id 
    validates :start_time_id
    validates :end_time_id
  end
  validate :time_start_end
  validate :day_start

  def self.search(search)
    if search != ""
      Event.where('name LIKE(?)', "%#{search}%") 
    else
      Event.all
    end
  end

  def time_start_end
    return if start_time_id.blank? || end_time_id.blank?
    errors.add(:end_time_id, "は開始時刻よりも後の時刻を選択してください") if start_time_id > end_time_id
  end

  def day_start
    return if day.blank?
    errors.add(:day, "は今日以降のものを選択してください") if day < Date.today
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only:[:new, :create, :edit, :update, :destroy]
  before_action :event_id_params, only:[:show, :edit, :update, :destroy]
  before_action :move_to_index_edit, only:[:edit, :destroy]
  before_action :search_event, only:[:index, :search]
  def index
    @events = Event.order("created_at DESC").page(params[:page]).per(6).includes(:user)
    set_event_column
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path, notice: 'イベントの投稿が完了しました'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path, notice: 'イベントの編集が完了しました'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path, notice: 'イベントが消去されました'
  end

  def search
    @events = @p.result.includes(:user)
    @events = @events.order("created_at DESC").page(params[:page]).per(6).includes(:user)
  end

  private

  def event_params
    params.require(:event).permit(:name, :image, :explanation, :genre_id, :day, :start_time_id, :end_time_id, :capacity, :area_id, :address).merge(user_id: current_user.id)
  end

  def event_id_params
    @event = Event.find(params[:id])
  end

  def move_to_index_edit
    if current_user.id != @event.user_id 
      redirect_to root_path
    end
  end

  def search_event
    @p = Event.ransack(params[:q])
    set_event_column
  end

  def set_event_column
    @events_genre = Genre.where.not(id:1)
    @events_area = Area.where.not(id:1)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event_form.html.erb
<%= form_with(model: @event, local: true) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <table class="events-table">
        <tbody>
          <tr>
            <th>
              イベント名
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.text_area :name, class:"event-form-default", id:"name", placeholder:"例) みんなでサッカーをしよう！", maxlength:"100", autofocus: true %>
            </td>
          </tr>
          <tr>
            <th>
              画像
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <p>
                クリックしてファイルをアップロード
              </p>
              <%= f.file_field :image, id:"item-image" %>
            </td>
          </tr>
          <tr>
            <th>
              イベントの内容
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.text_area :explanation, class:"event-text-default", id:"explanation", placeholder:"例) 公園でサッカーをみんなでやりたいと思います。せっかくの休みの日に汗を流しましょう！", rows:"7" ,maxlength:"1000" %>
            </td>
          </tr>
          <tr>
            <th>
              イベントのジャンル
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
            <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"event-form-default"}) %>
            </td>
          </tr>
          <tr>
            <th>
              日時
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td class="days">
              <%= raw sprintf(
                f.date_select(
                            :day,
                            {
                              id:"date",
                              use_month_numbers: true,
                              prompt:'--',
                              start_year: Time.now.year,
                              end_year: (Time.now.year + 5),
                              date_separator: '%s',
                            },
                            { class: 'date-select' }
                          ),
                          '年', '月') + '日'
              %>
                <br>
                  イベント開始時間
                  <br>
                    <%= f.collection_select(:start_time_id, StartTime.all, :id, :name, {}, {class:"event-time-default"}) %> ~ <%= f.collection_select(:end_time_id, EndTime.all, :id, :name, {}, {class:"event-time-default"}) %>
            </td>
          </tr>
          <tr>
            <th>
              予定人数
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.text_area :capacity, class:"event-capacity", id:"explanation", placeholder:"例)15" %>
            </td>
          </tr>
          <tr>
            <th>
              都道府県
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"event-form-default"}) %>
            </td>
          </tr>
          <tr>
            <th>
              開催場所
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.text_area :address, class:"event-form-default", id:"name", placeholder:"例) 〇〇体育館", maxlength:"100" %>
            </td>
          </tr>
        <tbody>
      </table>
      <div class='submit-double-btn'>
        <%= f.submit "募集内容を変更する" ,class:"submit-edit-btn" %>
        <%= link_to "変更しない", :back,class:"submit-back-btn" %>
      </div>
    <% end %>

app/views/events/_footer.html.erb
<footer class="footer">
      <div class="footer-logo">
            <%= link_to image_tag("footer-logo.png", class: :logo), root_path %>
      </div>
      <p class="copyright">Copyright © EVENT MATCHING All rights reserved.</p>
</footer>

app/views/events/_header-second.html.erb
<header class="header-second">
  <%= link_to image_tag("header-logo.png", class: "second-logo"), root_path %>
</header>

app/views/events/_header.html.erb
<header class="header">
  <div class="inner">
    <div class="nav">
      <div class="nav__left">
        <%= link_to image_tag("header-logo.png", class: :logo), root_path %>
      </div>
      <% if user_signed_in? %>
        
        <div class="nav__right">
          <span><%= link_to current_user.nickname, user_path(current_user.id), class: :login_user_name %>
            <ul class = "user_select">
              <li>
                <%= link_to "会員登録内容", mypage_user_path(current_user.id) %>
                <%= link_to "申し込み内容", user_path(current_user.id) %>
                <%= link_to "投稿内容", user_path(current_user.id) %>
              </li>
            </ul>
          </span>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: :nav__logout %>
          <%= link_to "イベント投稿", new_event_path, class: :nav__btn %>
        </div>
        
      <% else %>
        <div class="nav__right">
          <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
          <%= link_to "新規登録", new_user_path, class: :nav__btn %>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/events/_like.html.erb
<div class="like-icon">  
  <% if user_signed_in? %>
    <% if current_user.already_liked?(event) %>
      <%= link_to event_likes_path(event), method: :delete do %>
        <i class="fas fa-heart"></i>
      <%  end %>
    <% else%>
      <%= link_to event_likes_path(event), method: :post do %>
        <i class="far fa-heart"></i>
      <%  end %>
    <% end %>
    <%= event.likes.count %>
  <% else%>
    <%= link_to new_user_path  do %>
      <i class="far fa-heart"></i>
    <% end %>
    <%= event.likes.count %>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= render "header-second" %>
<div class="events-create-contents">
  <div class="event-create-main">
    <h1 class="events-create-title">イベントの編集</h1>
    <%= render "event_form" %>
  </div>
</div>
<%= render "footer" %>

app/views/events/index.html.erb
<%= render "header" %>
<div class="main-index">
  <%= search_form_for @p, url: search_events_path, local: true, method: :get, class: "search-form" do |form| %>
    <%= form.collection_select :genre_id_eq, @events_genre, :id, :name, include_blank: 'ジャンル' %>
    <%= form.collection_select :area_id_eq, @events_area, :id, :name, include_blank: '都道府県' %>
    <%= form.text_field :name_cont, placeholder: "イベントを検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  
  
  <div class="main-content">
    <div class="previews">
      <div class="slider">
          <%= image_tag 'home-image1' %>
          <%= image_tag 'home-image2' %>
          <%= image_tag 'home-image3' %>
          
      </div>
    </div>
    <div class="top-message">
    <h1>＜新しいイベント情報＞</h1>
    </div>
    <div class="event-count">
    <h2>現在のイベント募集数：<strong><%= @events.count %></strong>件<h2>
    </div>
    <ul class="main-list">
      <% @events.each do |event|%>
        <li class="event-info">
          <div class="sports-genre">      
            <%= event.genre.name %>
          </div>
          <div class="sports-area">
            <%= event.area.name %>
          </div>
          <%= link_to event_path(event.id), class:"img-link" do %>
            <%= image_tag event.image.variant(resize: '500x400') %>
          <% end %>
          <h2 class="event-name"><%= link_to event.name, event_path(event.id), class:"event-name-font" %></h2>
          <dl class="event-exp">
            <dt>
              <img src="https://images.e-venz.com/frontend/image/location.svg" class="Location lazy" alt="Location"><p class="event-text">開催場所：</p>
            </dt>
            <dd><%= event.address %></dd>
            <dt>
              <img src="https://images.e-venz.com/frontend/image/women.svg" alt="Women" class="lazy"><img src="https://images.e-venz.com/frontend/image/men.svg" alt="Men" class="lazy"> <p class="event-text">募集人数：</p>
            </dt>
            <dd><%= event.capacity %>人</dd>
            <dt>
              <img src="https://images.e-venz.com/frontend/image/calendar.svg" alt="Calendar" class="lazy"> <p class="event-text">開催日時：</p>
            </dt>
            <dd><%= event.day.month %>月<%= event.day.day %>日 <%= event.start_time.name %> ~ <%= event.end_time.name %></dd>
            <%= render partial: "like", locals: { event: event } %>

          </dl>
          
        </li>
      <% end %>
      <%= paginate @events %>
    <ul>
    
  </div>
</div>
<%= render "footer" %>

app/views/events/new.html.erb
<%= render "header-second" %>
<div class="events-create-contents">
  <div class="event-create-main">
    <h1 class="events-create-title">イベントの新規募集</h1>

    
    
    <%= form_with(model: @event, local: true) do |f| %>
      <%= render 'shared/error_messages', model: f.object %>

      <table class="events-table">
        <tbody>
          <tr>
            <th>
              イベント名
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.text_area :name, class:"event-form-default", id:"name", placeholder:"例) みんなでサッカーをしよう！", maxlength:"100", autofocus: true %>
            </td>
          </tr>
          <tr>
            <th>
              画像
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <p>
                クリックしてファイルをアップロード
              </p>
              <%= f.file_field :image, id:"item-image" %>
            </td>
          </tr>
          <tr>
            <th>
              イベントの内容
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.text_area :explanation, class:"event-text-default", id:"explanation", placeholder:"例) 公園でサッカーをみんなでやりたいと思います。せっかくの休みの日に汗を流しましょう！", rows:"7" ,maxlength:"1000" %>
            </td>
          </tr>
          <tr>
            <th>
              イベントのジャンル
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
            <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"event-form-default"}) %>
            </td>
          </tr>
          <tr>
            <th>
              日時
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td class="days">
              <%= raw sprintf(
                f.date_select(
                            :day,
                            {
                              id:"date",
                              use_month_numbers: true,
                              prompt:'--',
                              start_year: 2021,
                              end_year: (Time.now.year + 5),
                              date_separator: '%s',
                            },
                            { class: 'date-select' }
                          ),
                          '年', '月') + '日'
              %>
                <br>
                  イベント予定時刻
                  <br>
                    <%= f.collection_select(:start_time_id, StartTime.all, :id, :name, {}, {class:"event-time-default"}) %> ~ <%= f.collection_select(:end_time_id, EndTime.all, :id, :name, {}, {class:"event-time-default"}) %>
            </td>
          </tr>
          <tr>
            <th>
              予定人数
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.text_area :capacity, class:"event-capacity", id:"explanation", placeholder:"例)15" %>
            </td>
          </tr>
          <tr>
            <th>
              都道府県
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.collection_select(:area_id, Area.all, :id, :name, {}, {class:"event-form-default"}) %>
            </td>
          </tr>
          <tr>
            <th>
              開催場所
              <br>
              <span class="mandatory">必須</span>
            </th>
            <td>
              <%= f.text_area :address, class:"event-form-default", id:"gmap", placeholder:"例) 〇〇体育館", maxlength:"100" %>
            </td>
          </tr>
        <tbody>
      </table>
      <div class='submit-btn'>
        <%= f.submit "募集を開始する" ,class:"submit-btn-text" %>
      </div>
    <% end %>
  </div>
</div>
<%= render "footer" %>

app/views/events/search.html.erb
<%= render "header" %>
<div class="main-index">
  <%= search_form_for @p, url: search_events_path, local: true, method: :get, class: "search-form" do |form| %>
    <%= form.collection_select :genre_id_eq, @events_genre, :id, :name, include_blank: 'ジャンル' %>
    <%= form.collection_select :area_id_eq, @events_area, :id, :name, include_blank: '都道府県' %>
    <%= form.text_field :name_cont, placeholder: "イベントを検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>

  <div class="main-content">
    <div class="main-super">
    <%= image_tag "index-logo", class:"top-image" %>
    </div>
    <div class="top-message">
    <h1>＜新しいイベント情報＞</h1>
    </div>
    <% if @events.length !=0 %>
      <div class="event-count">
      <h2>現在のイベント募集数：<strong><%= @events.count %></strong>件<h2>
      </div>
      <ul class="main-list">
        <% @events.each do |event|%>
          <li class="event-info">
            <div class="sports-genre">      
              <%= event.genre.name %>
            </div>
            <div class="sports-area">
              <%= event.area.name %>
            </div>
            <%= link_to event_path(event.id), class:"img-link" do %>
              <%= image_tag event.image.variant(resize: '500x400') %>
            <% end %>
            <h2 class="event-name"><%= link_to event.name, event_path(event.id), class:"event-name-font" %></h2>
            <dl class="event-exp">
              <dt>
                <img src="https://images.e-venz.com/frontend/image/location.svg" class="Location lazy" alt="Location"><p class="event-text">開催場所：</p>
              </dt>
              <dd><%= event.address %></dd>
              <dt>
                <img src="https://images.e-venz.com/frontend/image/women.svg" alt="Women" class="lazy"><img src="https://images.e-venz.com/frontend/image/men.svg" alt="Men" class="lazy"> <p class="event-text">募集人数：</p>
              </dt>
              <dd><%= event.capacity %>人</dd>
              <dt>
                <img src="https://images.e-venz.com/frontend/image/calendar.svg" alt="Calendar" class="lazy"> <p class="event-text">開催日時：</p>
              </dt>
              <dd><%= event.day.month %>月<%= event.day.day %>日 <%= event.start_time.name %> ~ <%= event.end_time.name %></dd>
            </dl>
          </li>
        <% end %>
        <%= paginate @events %>
      <ul>
    <% else %>
      <div class="event-count">
        <h2>該当するイベントはありません</h2>
      </div>
    <% end %>
  </div>
</div>
<%= render "footer" %>

app/views/events/show.html.erb
<%= render "header" %>
<div class="events-main-contents">
  <div class="event-create-main">
    <h1 class="events-create-title"><%= @event.name %></h1>
  </div>

  <div class="event-super">
   <%= image_tag @event.image, class:"top-image" %>
  </div>
  <table class="events-table">
      <tbody>
        <tr>
          <th>
            イベント名
          </th>
          <td>
            <%= @event.name %>
          </td>
        </tr>
        <tr>
          <th>
            イベントの内容
          </th>
          <td>
            <%= @event.explanation %>
          </td>
        </tr>
        <tr>
          <th>
            イベントのジャンル
          </th>
          <td>
           <%= @event.genre.name %>
          </td>
        </tr>
        <tr>
          <th>
            イベントの日時
          </th>
          <td>
           <%= @event.day.month %>月<%= @event.day.day %>日 <%= @event.start_time.name %> ~ <%= @event.end_time.name %>
          </td>
        </tr>
        <tr>
          <th>
            予定人数
          </th>
          <td>
           <%= @event.capacity %>人
          </td>
        </tr>
        <tr>
          <th>
            現在の人数
          </th>
          <td>
            <%= @event.entries.count %>人
          </td>
        </tr>
        <tr>
          <th>
            都道府県
          </th>
          <td>
           <%= @event.area.name %>
          </td>
        </tr>
        <tr>
          <th>
            開催場所
          </th>
          <td>
           <%= @event.address  %>
           <div id="map", class="event-map"></div>
           <script>
            let map
            function initMap(){
              map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: <%= @event.latitude %>, lng: <%= @event.longitude %>},
                zoom: 15,
                  zoomControl: true,
                  mapTypeControl: false,
                  fullscreenControl: false,
                  streetViewControl: false,
              });

              marker = new google.maps.Marker({
                position: {lat: <%= @event.latitude %>, lng: <%= @event.longitude %>},
                map: map
              });
              geocoder = new google.maps.Geocoder()
            }
           </script>
              <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async defer></script>
          </td>
        </tr>
        <tr>
          <th>
            イベント投稿者
          </th>
          <td>
           <%= link_to @event.user.nickname, user_path(@event.user_id) %>
          </td>
        </tr>
      </tbody>
  </table>
  <% if user_signed_in? %>
    <% if current_user.id == @event.user_id  %> 
      <div class="event-edit-btn">
        <%= link_to "イベントの編集", edit_event_path(@event.id), method: :get, class: "edit-path-btn" %>
        <%= link_to "イベントの削除", event_path(@event.id), method: :delete, data: { confirm: '削除しますか？' }, class: "delete-path-btn" %>
      </div>
    <% elsif ! current_user.entried_by?(@event.id) %>
      <div class="event-entry-btn">
        <%= link_to "申し込みをする", event_entries_path(@event.id),class:"entry-btn" %>
      </div>
    <% else%>
      <h1 class="entry-later-logo">申し込み済みのイベントです</h1>
    <% end %>
  <% else%>
    <div class="event-entry-btn">
        <%= link_to "申し込みをする", new_user_session_path,class:"entry-btn" %>
    </div>
  <% end %>
</div>
<%= render "events/footer" %>